export {
  listEntriesHygienistsGetOptions as listHygienistsOptions,
  listEntriesHygienistsGetQueryKey as listHygienistsQueryKey,
  getHygienistHygienistsHygienistIdGetOptions as getHygienistOptions,
  getHygienistHygienistsHygienistIdGetQueryKey as getHygienistQueryKey,
  createHygienistHygienistsPostMutation as createHygienistMutation,
  updateHygienistHygienistsHygienistIdPatchMutation as updateHygienistMutation,
  wrapperHygienistsHygienistIdDeleteMutation as deleteHygienistMutation,
  wrapperHygienistsHygienistIdConnectionsGetOptions as getHygienistConnectionsOptions,
  wrapperHygienistsHygienistIdConnectionsGetQueryKey as getHygienistConnectionsQueryKey,
} from "@/api/generated/@tanstack/react-query.gen";
