export {
  listEntriesHygienistsGetOptions as listHygienistsOptions,
  listEntriesHygienistsGetQueryKey as listHygienistsQueryKey,
  getHygienistHygienistsHygienistIdGetOptions as getHygienistOptions,
  getHygienistHygienistsHygienistIdGetQueryKey as getHygienistQueryKey,
  createHygienistHygienistsPostMutation as createHygienistMutation,
  updateHygienistHygienistsHygienistIdPatchMutation as updateHygienistMutation,
  deleteHygienistHygienistsHygienistIdDeleteMutation as deleteHygienistMutation,
  getHygienistConnectionsHygienistsHygienistIdConnectionsGetOptions as getHygienistConnectionsOptions,
  getHygienistConnectionsHygienistsHygienistIdConnectionsGetQueryKey as getHygienistConnectionsQueryKey,
} from "@/api/generated/@tanstack/react-query.gen";
