"""add is_saved to work_auths, enforce one wa per project

Revision ID: b0f64c751b09
Revises: c0664b72d27b
Create Date: 2026-04-10 11:47:26.834590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f64c751b09'
down_revision: Union[str, Sequence[str], None] = 'c0664b72d27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_auths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_saved', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_index(batch_op.f('ix_work_auths_project_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_work_auths_project_id'), ['project_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_auths', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_work_auths_project_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_work_auths_project_id'), ['project_id'], unique=False)
        batch_op.drop_column('is_saved')

    # ### end Alembic commands ###
