"""Added project_num column to projects table

Revision ID: bf7e5798598e
Revises: f04316898db3
Create Date: 2026-04-01 16:46:48.716776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7e5798598e'
down_revision: Union[str, Sequence[str], None] = 'f04316898db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_number', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_project_number'), ['project_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_number'))
        batch_op.drop_column('project_number')

    # ### end Alembic commands ###
