"""add work_auths table

Revision ID: c0664b72d27b
Revises: 89dc900d1b0d
Create Date: 2026-04-10 11:38:43.563784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0664b72d27b'
down_revision: Union[str, Sequence[str], None] = '89dc900d1b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_num', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('project_num', sa.String(length=50), nullable=False),
    sa.Column('initiation_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_work_auths_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_work_auths_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_work_auths_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_auths'))
    )
    with op.batch_alter_table('work_auths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_auths_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_auths_project_num'), ['project_num'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_auths_service_id'), ['service_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_auths_wa_num'), ['wa_num'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_auths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_auths_wa_num'))
        batch_op.drop_index(batch_op.f('ix_work_auths_service_id'))
        batch_op.drop_index(batch_op.f('ix_work_auths_project_num'))
        batch_op.drop_index(batch_op.f('ix_work_auths_project_id'))

    op.drop_table('work_auths')
    # ### end Alembic commands ###
