"""create project contractor link table

Revision ID: f04316898db3
Revises: 
Create Date: 2026-04-01 16:02:56.208876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04316898db3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=14),
               existing_nullable=True)

    with op.batch_alter_table('project_contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.create_index(batch_op.f('ix_projects_title'), ['title'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('project_contractors', schema=None) as batch_op:
        batch_op.drop_column('assigned_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
