/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminWaCodesIndexRouteImport } from './routes/_authenticated/admin/wa-codes/index'
import { Route as AuthenticatedAdminSchoolsIndexRouteImport } from './routes/_authenticated/admin/schools/index'
import { Route as AuthenticatedAdminEmployeesIndexRouteImport } from './routes/_authenticated/admin/employees/index'
import { Route as AuthenticatedAdminWaCodesWaCodeIdRouteImport } from './routes/_authenticated/admin/wa-codes/$waCodeId'
import { Route as AuthenticatedAdminSchoolsSchoolIdRouteImport } from './routes/_authenticated/admin/schools/$schoolId'
import { Route as AuthenticatedAdminEmployeesEmployeeIdRouteImport } from './routes/_authenticated/admin/employees/$employeeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWaCodesIndexRoute =
  AuthenticatedAdminWaCodesIndexRouteImport.update({
    id: '/wa-codes/',
    path: '/wa-codes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSchoolsIndexRoute =
  AuthenticatedAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesIndexRoute =
  AuthenticatedAdminEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWaCodesWaCodeIdRoute =
  AuthenticatedAdminWaCodesWaCodeIdRouteImport.update({
    id: '/wa-codes/$waCodeId',
    path: '/wa-codes/$waCodeId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSchoolsSchoolIdRoute =
  AuthenticatedAdminSchoolsSchoolIdRouteImport.update({
    id: '/schools/$schoolId',
    path: '/schools/$schoolId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesEmployeeIdRoute =
  AuthenticatedAdminEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/admin/employees/$employeeId': typeof AuthenticatedAdminEmployeesEmployeeIdRoute
  '/admin/schools/$schoolId': typeof AuthenticatedAdminSchoolsSchoolIdRoute
  '/admin/wa-codes/$waCodeId': typeof AuthenticatedAdminWaCodesWaCodeIdRoute
  '/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/schools/': typeof AuthenticatedAdminSchoolsIndexRoute
  '/admin/wa-codes/': typeof AuthenticatedAdminWaCodesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/admin/employees/$employeeId': typeof AuthenticatedAdminEmployeesEmployeeIdRoute
  '/admin/schools/$schoolId': typeof AuthenticatedAdminSchoolsSchoolIdRoute
  '/admin/wa-codes/$waCodeId': typeof AuthenticatedAdminWaCodesWaCodeIdRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsIndexRoute
  '/admin/wa-codes': typeof AuthenticatedAdminWaCodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/admin/employees/$employeeId': typeof AuthenticatedAdminEmployeesEmployeeIdRoute
  '/_authenticated/admin/schools/$schoolId': typeof AuthenticatedAdminSchoolsSchoolIdRoute
  '/_authenticated/admin/wa-codes/$waCodeId': typeof AuthenticatedAdminWaCodesWaCodeIdRoute
  '/_authenticated/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/_authenticated/admin/schools/': typeof AuthenticatedAdminSchoolsIndexRoute
  '/_authenticated/admin/wa-codes/': typeof AuthenticatedAdminWaCodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/admin/'
    | '/projects/'
    | '/admin/employees/$employeeId'
    | '/admin/schools/$schoolId'
    | '/admin/wa-codes/$waCodeId'
    | '/admin/employees/'
    | '/admin/schools/'
    | '/admin/wa-codes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/admin'
    | '/projects'
    | '/admin/employees/$employeeId'
    | '/admin/schools/$schoolId'
    | '/admin/wa-codes/$waCodeId'
    | '/admin/employees'
    | '/admin/schools'
    | '/admin/wa-codes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/admin/'
    | '/_authenticated/projects/'
    | '/_authenticated/admin/employees/$employeeId'
    | '/_authenticated/admin/schools/$schoolId'
    | '/_authenticated/admin/wa-codes/$waCodeId'
    | '/_authenticated/admin/employees/'
    | '/_authenticated/admin/schools/'
    | '/_authenticated/admin/wa-codes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wa-codes/': {
      id: '/_authenticated/admin/wa-codes/'
      path: '/wa-codes'
      fullPath: '/admin/wa-codes/'
      preLoaderRoute: typeof AuthenticatedAdminWaCodesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schools/': {
      id: '/_authenticated/admin/schools/'
      path: '/schools'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees/': {
      id: '/_authenticated/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wa-codes/$waCodeId': {
      id: '/_authenticated/admin/wa-codes/$waCodeId'
      path: '/wa-codes/$waCodeId'
      fullPath: '/admin/wa-codes/$waCodeId'
      preLoaderRoute: typeof AuthenticatedAdminWaCodesWaCodeIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schools/$schoolId': {
      id: '/_authenticated/admin/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/admin/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees/$employeeId': {
      id: '/_authenticated/admin/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmployeesEmployeeIdRoute: typeof AuthenticatedAdminEmployeesEmployeeIdRoute
  AuthenticatedAdminSchoolsSchoolIdRoute: typeof AuthenticatedAdminSchoolsSchoolIdRoute
  AuthenticatedAdminWaCodesWaCodeIdRoute: typeof AuthenticatedAdminWaCodesWaCodeIdRoute
  AuthenticatedAdminEmployeesIndexRoute: typeof AuthenticatedAdminEmployeesIndexRoute
  AuthenticatedAdminSchoolsIndexRoute: typeof AuthenticatedAdminSchoolsIndexRoute
  AuthenticatedAdminWaCodesIndexRoute: typeof AuthenticatedAdminWaCodesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEmployeesEmployeeIdRoute:
    AuthenticatedAdminEmployeesEmployeeIdRoute,
  AuthenticatedAdminSchoolsSchoolIdRoute:
    AuthenticatedAdminSchoolsSchoolIdRoute,
  AuthenticatedAdminWaCodesWaCodeIdRoute:
    AuthenticatedAdminWaCodesWaCodeIdRoute,
  AuthenticatedAdminEmployeesIndexRoute: AuthenticatedAdminEmployeesIndexRoute,
  AuthenticatedAdminSchoolsIndexRoute: AuthenticatedAdminSchoolsIndexRoute,
  AuthenticatedAdminWaCodesIndexRoute: AuthenticatedAdminWaCodesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
