"""made employee role table

Revision ID: 10da7ad67b78
Revises: f60a02bc3b29
Create Date: 2026-04-24 15:06:22.199537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10da7ad67b78'
down_revision: Union[str, Sequence[str], None] = 'f60a02bc3b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_role_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employee_role_types_name'), type_='unique')

    with op.batch_alter_table('employee_roles', schema=None) as batch_op:
        batch_op.alter_column('role_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_employee_roles_role_type_id_employee_role_types'), 'employee_role_types', ['role_type_id'], ['id'])
        batch_op.drop_column('role_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_type', sa.VARCHAR(length=22), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_employee_roles_role_type_id_employee_role_types'), type_='foreignkey')
        batch_op.alter_column('role_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employee_role_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employee_role_types_name'), ['name'])

    # ### end Alembic commands ###
