"""added more status enums and nullable batch time entries

Revision ID: 15ea0116b678
Revises: a9ba37140907
Create Date: 2026-04-15 14:50:18.170058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ea0116b678'
down_revision: Union[str, Sequence[str], None] = 'a9ba37140907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'DISCARDED', 'LOCKED', name='samplebatchstatus'), server_default='active', nullable=False))
        batch_op.alter_column('time_entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ASSUMED', 'ENTERED', 'LOCKED', name='timeentrystatus'), server_default='entered', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.alter_column('time_entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
