"""initial

Revision ID: 2e1e76a80ee7
Revises: 
Create Date: 2026-04-28 11:22:07.183034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1e76a80ee7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_users_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_contractors_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_contractors_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractors'))
    )
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractors_name'), ['name'], unique=False)

    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Enum('PROJECT', 'BUILDING', name='wacodelevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_deliverables_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_deliverables_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverables'))
    )
    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliverables_name'), ['name'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Enum('MR', 'MS', 'MRS', name='titleenum'), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=14), nullable=True),
    sa.Column('adp_id', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employees_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employees_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('adp_id', name=op.f('uq_employees_adp_id')),
    sa.UniqueConstraint('display_name', name=op.f('uq_employees_display_name')),
    sa.UniqueConstraint('email', name=op.f('uq_employees_email'))
    )
    op.create_table('hygienists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=14), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_hygienists_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_hygienists_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hygienists')),
    sa.UniqueConstraint('email', name=op.f('uq_hygienists_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_hygienists_phone'))
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PROJECT', 'TIME_ENTRY', 'DELIVERABLE', 'SAMPLE_BATCH', 'CONTRACTOR_PAYMENT_RECORD', name='noteentitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('parent_note_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('TIME_ENTRY_CONFLICT', 'MISSING_SAMPLE_TYPE_WA_CODE', 'CPR_STAGE_REGRESSION', name='notetype'), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_notes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_note_id'], ['notes.id'], name=op.f('fk_notes_parent_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_notes_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_notes_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_parent_note_id'), ['parent_note_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_number', sa.String(length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_projects_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_number'), ['project_number'], unique=True)

    op.create_table('sample_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allows_multiple_inspectors', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sample_types_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sample_types_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_types'))
    )
    with op.batch_alter_table('sample_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_types_name'), ['name'], unique=True)

    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.Enum('BROOKLYN', 'MANHATTAN', 'BRONX', 'QUEENS', 'STATEN_ISLAND', name='boro'), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_schools_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_schools_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=True)

    op.create_table('wa_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('PROJECT', 'BUILDING', name='wacodelevel'), nullable=False),
    sa.Column('default_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_wa_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_wa_codes_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wa_codes')),
    sa.UniqueConstraint('description', name=op.f('uq_wa_codes_description'))
    )
    with op.batch_alter_table('wa_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wa_codes_code'), ['code'], unique=True)

    op.create_table('contractor_payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('rfa_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('rfa_internal_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='cprstagestatus'), nullable=True),
    sa.Column('rfa_internal_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('rfa_sca_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='cprstagestatus'), nullable=True),
    sa.Column('rfa_sca_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('rfp_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('rfp_internal_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='cprstagestatus'), nullable=True),
    sa.Column('rfp_internal_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('rfp_saved_at', sa.DateTime(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('dismissal_reason', sa.Text(), nullable=True),
    sa.Column('dismissed_by_id', sa.Integer(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_contractor_payment_records_contractor_id_contractors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_contractor_payment_records_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dismissed_by_id'], ['users.id'], name=op.f('fk_contractor_payment_records_dismissed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_contractor_payment_records_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_contractor_payment_records_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractor_payment_records'))
    )
    with op.batch_alter_table('contractor_payment_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractor_payment_records_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractor_payment_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_cpr_status', ['project_id', 'rfp_saved_at', 'dismissed_at'], unique=False)
        batch_op.create_index('ix_uq_cpr_active', ['project_id', 'contractor_id'], unique=True, sqlite_where=sa.text('dismissed_at IS NULL'))

    op.create_table('deliverable_wa_code_triggers',
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], name=op.f('fk_deliverable_wa_code_triggers_deliverable_id_deliverables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_deliverable_wa_code_triggers_wa_code_id_wa_codes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deliverable_id', 'wa_code_id', name=op.f('pk_deliverable_wa_code_triggers'))
    )
    op.create_table('employee_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.Enum('ACM_AIR_TECH', 'ACM_PROJECT_MONITOR', 'ACM_INSPECTOR_A', 'ACM_INVESTIGATOR_A', 'ACM_PROJECT_MANAGER_A', 'LBP_RISK_ASSESSOR_A', 'LBP_RISK_ASSESSOR_B', 'MOLD_FIELD_TECH', 'MOLD_PROJECT_MANAGER_A', 'MOLD_PROJECT_MANAGER_B', name='employeeroletype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_roles_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_roles_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_roles_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_roles'))
    )
    with op.batch_alter_table('employee_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_roles_employee_id'), ['employee_id'], unique=False)

    op.create_table('project_contractors_links',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_project_contractors_links_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_contractors_links_project_id_projects')),
    sa.PrimaryKeyConstraint('project_id', 'contractor_id', name=op.f('pk_project_contractors_links'))
    )
    op.create_table('project_deliverables',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('internal_status', sa.Enum('INCOMPLETE', 'BLOCKED', 'IN_REVIEW', 'IN_REVISION', 'COMPLETED', name='internaldeliverablestatus'), nullable=False),
    sa.Column('sca_status', sa.Enum('PENDING_WA', 'PENDING_RFA', 'OUTSTANDING', 'UNDER_REVIEW', 'REJECTED', 'APPROVED', name='scadeliverablestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_project_deliverables_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], name=op.f('fk_project_deliverables_deliverable_id_deliverables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_deliverables_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_project_deliverables_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('project_id', 'deliverable_id', name=op.f('pk_project_deliverables'))
    )
    op.create_table('project_hygienist_links',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('hygienist_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hygienist_id'], ['hygienists.id'], name=op.f('fk_project_hygienist_links_hygienist_id_hygienists'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_hygienist_links_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_hygienist_links'))
    )
    op.create_table('project_manager_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_project_manager_assignments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_manager_assignments_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_manager_assignments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_manager_assignments'))
    )
    with op.batch_alter_table('project_manager_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_manager_assignments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_manager_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('project_school_links',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_school_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_project_school_links_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'school_id', name=op.f('pk_project_school_links'))
    )
    op.create_table('sample_subtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sample_subtypes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], name=op.f('fk_sample_subtypes_sample_type_id_sample_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sample_subtypes_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_subtypes'))
    )
    with op.batch_alter_table('sample_subtypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_subtypes_sample_type_id'), ['sample_type_id'], unique=False)

    op.create_table('sample_type_required_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_type_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.Enum('ACM_AIR_TECH', 'ACM_PROJECT_MONITOR', 'ACM_INSPECTOR_A', 'ACM_INVESTIGATOR_A', 'ACM_PROJECT_MANAGER_A', 'LBP_RISK_ASSESSOR_A', 'LBP_RISK_ASSESSOR_B', 'MOLD_FIELD_TECH', 'MOLD_PROJECT_MANAGER_A', 'MOLD_PROJECT_MANAGER_B', name='employeeroletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sample_type_required_roles_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], name=op.f('fk_sample_type_required_roles_sample_type_id_sample_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sample_type_required_roles_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_type_required_roles')),
    sa.UniqueConstraint('sample_type_id', 'role_type', name='uq_sample_type_required_roles')
    )
    with op.batch_alter_table('sample_type_required_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_type_required_roles_sample_type_id'), ['sample_type_id'], unique=False)

    op.create_table('sample_type_wa_codes',
    sa.Column('sample_type_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sample_type_wa_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], name=op.f('fk_sample_type_wa_codes_sample_type_id_sample_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sample_type_wa_codes_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_sample_type_wa_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sample_type_id', 'wa_code_id', name=op.f('pk_sample_type_wa_codes'))
    )
    op.create_table('sample_unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sample_unit_types_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], name=op.f('fk_sample_unit_types_sample_type_id_sample_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sample_unit_types_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_unit_types'))
    )
    with op.batch_alter_table('sample_unit_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_unit_types_sample_type_id'), ['sample_type_id'], unique=False)

    op.create_table('turnaround_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_type_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_turnaround_options_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], name=op.f('fk_turnaround_options_sample_type_id_sample_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_turnaround_options_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turnaround_options'))
    )
    with op.batch_alter_table('turnaround_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnaround_options_sample_type_id'), ['sample_type_id'], unique=False)

    op.create_table('work_auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_num', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('project_num', sa.String(length=50), nullable=False),
    sa.Column('initiation_date', sa.Date(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_work_auths_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_work_auths_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_work_auths_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_auths')),
    sa.UniqueConstraint('project_id', name=op.f('uq_work_auths_project_id'))
    )
    with op.batch_alter_table('work_auths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_auths_project_num'), ['project_num'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_auths_service_id'), ['service_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_auths_wa_num'), ['wa_num'], unique=True)

    op.create_table('project_building_deliverables',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('internal_status', sa.Enum('INCOMPLETE', 'BLOCKED', 'IN_REVIEW', 'IN_REVISION', 'COMPLETED', name='internaldeliverablestatus'), nullable=False),
    sa.Column('sca_status', sa.Enum('PENDING_WA', 'PENDING_RFA', 'OUTSTANDING', 'UNDER_REVIEW', 'REJECTED', 'APPROVED', name='scadeliverablestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_project_building_deliverables_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], name=op.f('fk_project_building_deliverables_deliverable_id_deliverables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_project_building_deliverables_project_id_project_school_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_building_deliverables_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_project_building_deliverables_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('project_id', 'deliverable_id', 'school_id', name=op.f('pk_project_building_deliverables'))
    )
    op.create_table('rfas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_auth_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='rfastatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_rfas_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_rfas_submitted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_rfas_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_auth_id'], ['work_auths.id'], name=op.f('fk_rfas_work_auth_id_work_auths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfas'))
    )
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_role_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ASSUMED', 'ENTERED', 'LOCKED', name='timeentrystatus'), server_default='entered', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_time_entries_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_time_entries_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_role_id'], ['employee_roles.id'], name=op.f('fk_time_entries_employee_role_id_employee_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_time_entries_project_id_project_school_links'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_time_entries_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_time_entries_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_employee_role_id'), ['employee_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_school_id'), ['school_id'], unique=False)

    op.create_table('work_auth_building_codes',
    sa.Column('work_auth_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RFA_NEEDED', 'RFA_PENDING', 'ACTIVE', 'ADDED_BY_RFA', 'REMOVED', name='wacodestatus'), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_work_auth_building_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_work_auth_building_codes_project_id_project_school_links'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_work_auth_building_codes_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_work_auth_building_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_auth_id'], ['work_auths.id'], name=op.f('fk_work_auth_building_codes_work_auth_id_work_auths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_auth_id', 'wa_code_id', 'project_id', 'school_id', name=op.f('pk_work_auth_building_codes'))
    )
    op.create_table('work_auth_project_codes',
    sa.Column('work_auth_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RFA_NEEDED', 'RFA_PENDING', 'ACTIVE', 'ADDED_BY_RFA', 'REMOVED', name='wacodestatus'), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_work_auth_project_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_work_auth_project_codes_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_work_auth_project_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_auth_id'], ['work_auths.id'], name=op.f('fk_work_auth_project_codes_work_auth_id_work_auths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_auth_id', 'wa_code_id', name=op.f('pk_work_auth_project_codes'))
    )
    op.create_table('rfa_building_codes',
    sa.Column('rfa_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'REMOVE', name='rfaaction'), nullable=False),
    sa.Column('budget_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_rfa_building_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_rfa_building_codes_project_id_project_school_links'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfa_id'], ['rfas.id'], name=op.f('fk_rfa_building_codes_rfa_id_rfas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_rfa_building_codes_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_rfa_building_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rfa_id', 'wa_code_id', 'project_id', 'school_id', name=op.f('pk_rfa_building_codes'))
    )
    op.create_table('rfa_project_codes',
    sa.Column('rfa_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'REMOVE', name='rfaaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_rfa_project_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfa_id'], ['rfas.id'], name=op.f('fk_rfa_project_codes_rfa_id_rfas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_rfa_project_codes_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_rfa_project_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rfa_id', 'wa_code_id', name=op.f('pk_rfa_project_codes'))
    )
    op.create_table('sample_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_type_id', sa.Integer(), nullable=False),
    sa.Column('sample_subtype_id', sa.Integer(), nullable=True),
    sa.Column('turnaround_option_id', sa.Integer(), nullable=True),
    sa.Column('time_entry_id', sa.Integer(), nullable=True),
    sa.Column('batch_num', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCARDED', 'LOCKED', name='samplebatchstatus'), server_default='active', nullable=False),
    sa.Column('date_collected', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sample_batches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_subtype_id'], ['sample_subtypes.id'], name=op.f('fk_sample_batches_sample_subtype_id_sample_subtypes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], name=op.f('fk_sample_batches_sample_type_id_sample_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name=op.f('fk_sample_batches_time_entry_id_time_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turnaround_option_id'], ['turnaround_options.id'], name=op.f('fk_sample_batches_turnaround_option_id_turnaround_options'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sample_batches_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_batches'))
    )
    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_batches_batch_num'), ['batch_num'], unique=True)
        batch_op.create_index(batch_op.f('ix_sample_batches_sample_type_id'), ['sample_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_batches_time_entry_id'), ['time_entry_id'], unique=False)

    op.create_table('sample_batch_inspectors',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['sample_batches.id'], name=op.f('fk_sample_batch_inspectors_batch_id_sample_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_sample_batch_inspectors_employee_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('batch_id', 'employee_id', name=op.f('pk_sample_batch_inspectors'))
    )
    op.create_table('sample_batch_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sample_unit_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['sample_batches.id'], name=op.f('fk_sample_batch_units_batch_id_sample_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_unit_type_id'], ['sample_unit_types.id'], name=op.f('fk_sample_batch_units_sample_unit_type_id_sample_unit_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_batch_units'))
    )
    with op.batch_alter_table('sample_batch_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_batch_units_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_batch_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_batch_units_batch_id'))

    op.drop_table('sample_batch_units')
    op.drop_table('sample_batch_inspectors')
    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_batches_time_entry_id'))
        batch_op.drop_index(batch_op.f('ix_sample_batches_sample_type_id'))
        batch_op.drop_index(batch_op.f('ix_sample_batches_batch_num'))

    op.drop_table('sample_batches')
    op.drop_table('rfa_project_codes')
    op.drop_table('rfa_building_codes')
    op.drop_table('work_auth_project_codes')
    op.drop_table('work_auth_building_codes')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_school_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_employee_role_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_employee_id'))

    op.drop_table('time_entries')
    op.drop_table('rfas')
    op.drop_table('project_building_deliverables')
    with op.batch_alter_table('work_auths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_auths_wa_num'))
        batch_op.drop_index(batch_op.f('ix_work_auths_service_id'))
        batch_op.drop_index(batch_op.f('ix_work_auths_project_num'))

    op.drop_table('work_auths')
    with op.batch_alter_table('turnaround_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnaround_options_sample_type_id'))

    op.drop_table('turnaround_options')
    with op.batch_alter_table('sample_unit_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_unit_types_sample_type_id'))

    op.drop_table('sample_unit_types')
    op.drop_table('sample_type_wa_codes')
    with op.batch_alter_table('sample_type_required_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_type_required_roles_sample_type_id'))

    op.drop_table('sample_type_required_roles')
    with op.batch_alter_table('sample_subtypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_subtypes_sample_type_id'))

    op.drop_table('sample_subtypes')
    op.drop_table('project_school_links')
    with op.batch_alter_table('project_manager_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_manager_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_manager_assignments_project_id'))

    op.drop_table('project_manager_assignments')
    op.drop_table('project_hygienist_links')
    op.drop_table('project_deliverables')
    op.drop_table('project_contractors_links')
    with op.batch_alter_table('employee_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_roles_employee_id'))

    op.drop_table('employee_roles')
    op.drop_table('deliverable_wa_code_triggers')
    with op.batch_alter_table('contractor_payment_records', schema=None) as batch_op:
        batch_op.drop_index('ix_uq_cpr_active', sqlite_where=sa.text('dismissed_at IS NULL'))
        batch_op.drop_index('ix_cpr_status')
        batch_op.drop_index(batch_op.f('ix_contractor_payment_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_contractor_payment_records_contractor_id'))

    op.drop_table('contractor_payment_records')
    with op.batch_alter_table('wa_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wa_codes_code'))

    op.drop_table('wa_codes')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_code'))

    op.drop_table('schools')
    with op.batch_alter_table('sample_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_types_name'))

    op.drop_table('sample_types')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_number'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_parent_note_id'))
        batch_op.drop_index('ix_notes_entity')

    op.drop_table('notes')
    op.drop_table('hygienists')
    op.drop_table('employees')
    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliverables_name'))

    op.drop_table('deliverables')
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractors_name'))

    op.drop_table('contractors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
