"""add work_auth_project_codes and work_auth_building_codes

Revision ID: 3d09df0c7a96
Revises: b0f64c751b09
Create Date: 2026-04-10 11:58:37.822977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d09df0c7a96'
down_revision: Union[str, Sequence[str], None] = 'b0f64c751b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_auth_building_codes',
    sa.Column('work_auth_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RFA_NEEDED', 'RFA_PENDING', 'ACTIVE', 'ADDED_BY_RFA', 'REMOVED', name='wacodestatus'), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_work_auth_building_codes_project_id_project_school_links'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_work_auth_building_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_auth_id'], ['work_auths.id'], name=op.f('fk_work_auth_building_codes_work_auth_id_work_auths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_auth_id', 'wa_code_id', 'project_id', 'school_id', name=op.f('pk_work_auth_building_codes'))
    )
    op.create_table('work_auth_project_codes',
    sa.Column('work_auth_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RFA_NEEDED', 'RFA_PENDING', 'ACTIVE', 'ADDED_BY_RFA', 'REMOVED', name='wacodestatus'), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_work_auth_project_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_auth_id'], ['work_auths.id'], name=op.f('fk_work_auth_project_codes_work_auth_id_work_auths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_auth_id', 'wa_code_id', name=op.f('pk_work_auth_project_codes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_auth_project_codes')
    op.drop_table('work_auth_building_codes')
    # ### end Alembic commands ###
