"""Added is_locker column to projects

Revision ID: 63cdb503fb16
Revises: 2e8f8dab8f43
Create Date: 2026-04-16 16:49:31.130940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cdb503fb16'
down_revision: Union[str, Sequence[str], None] = '2e8f8dab8f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('note_type',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('TIME_ENTRY_CONFLICT', 'MISSING_SAMPLE_TYPE_WA_CODE', name='notetype'),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('note_type',
               existing_type=sa.Enum('TIME_ENTRY_CONFLICT', 'MISSING_SAMPLE_TYPE_WA_CODE', name='notetype'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=True)

    # ### end Alembic commands ###
