"""empty message

Revision ID: 811f454863ac
Revises: c32c2f8d3c75
Create Date: 2026-04-10 20:49:02.388674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811f454863ac'
down_revision: Union[str, Sequence[str], None] = 'c32c2f8d3c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_employees')
    with op.batch_alter_table('project_building_deliverables', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_project_building_deliverables_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_building_deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_building_deliverables_project_id_projects'), type_='foreignkey')

    op.create_table('_alembic_tmp_employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=3), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=14), nullable=True),
    sa.Column('adp_id', sa.VARCHAR(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('adp_id', name=op.f('uq_employees_adp_id'))
    )
    # ### end Alembic commands ###
