"""add default_fee to wa_codes

Revision ID: a00153cd5eb2
Revises: 3d09df0c7a96
Create Date: 2026-04-10 12:16:46.585275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00153cd5eb2'
down_revision: Union[str, Sequence[str], None] = '3d09df0c7a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_codes', schema=None) as batch_op:
        batch_op.drop_column('default_fee')

    # ### end Alembic commands ###
