"""added audit columns to most tables

Revision ID: a9ba37140907
Revises: 18485871da1f
Create Date: 2026-04-13 20:47:59.058879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ba37140907'
down_revision: Union[str, Sequence[str], None] = '18485871da1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_role_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_time_entries_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_time_entries_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_role_id'], ['employee_roles.id'], name=op.f('fk_time_entries_employee_role_id_employee_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_time_entries_project_id_project_school_links'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_time_entries_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_time_entries_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_employee_role_id'), ['employee_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_school_id'), ['school_id'], unique=False)

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contractors_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contractors_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_deliverables_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_deliverables_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employee_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_employee_roles_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_employee_roles_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_employees_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_employees_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('hygienists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_hygienists_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_hygienists_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_building_deliverables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project_building_deliverables_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_project_building_deliverables_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_deliverables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project_deliverables_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_project_deliverables_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rfa_building_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rfa_building_codes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_rfa_building_codes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rfa_project_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rfa_project_codes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_rfa_project_codes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sample_batches_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sample_batches_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sample_subtypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sample_subtypes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sample_subtypes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sample_type_required_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sample_type_required_roles_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sample_type_required_roles_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sample_type_wa_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sample_type_wa_codes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sample_type_wa_codes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sample_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sample_types_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sample_types_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sample_unit_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sample_unit_types_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sample_unit_types_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('turnaround_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_turnaround_options_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_turnaround_options_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('wa_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_wa_codes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_wa_codes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('work_auth_building_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_work_auth_building_codes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_work_auth_building_codes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('work_auth_project_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_work_auth_project_codes_created_by_id_users'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_work_auth_project_codes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_auth_project_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_work_auth_project_codes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_work_auth_project_codes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('work_auth_building_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_work_auth_building_codes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_work_auth_building_codes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('wa_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_wa_codes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_wa_codes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('turnaround_options', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_turnaround_options_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_turnaround_options_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sample_unit_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sample_unit_types_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sample_unit_types_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sample_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sample_types_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sample_types_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sample_type_wa_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sample_type_wa_codes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sample_type_wa_codes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sample_type_required_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sample_type_required_roles_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sample_type_required_roles_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sample_subtypes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sample_subtypes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sample_subtypes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sample_batches_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sample_batches_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('rfa_project_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rfa_project_codes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_rfa_project_codes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('rfa_building_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rfa_building_codes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_rfa_building_codes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('project_deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_deliverables_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_deliverables_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('project_building_deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_building_deliverables_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_building_deliverables_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('hygienists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hygienists_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_hygienists_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employees_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_employees_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('employee_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employee_roles_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_employee_roles_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deliverables_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_deliverables_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contractors_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contractors_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_school_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_employee_role_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_employee_id'))

    op.drop_table('time_entries')
    # ### end Alembic commands ###
