"""add rfas rfa_project_codes rfa_building_codes

Revision ID: c32c2f8d3c75
Revises: a00153cd5eb2
Create Date: 2026-04-10 16:16:25.952257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32c2f8d3c75'
down_revision: Union[str, Sequence[str], None] = 'a00153cd5eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_auth_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='rfastatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_rfas_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_rfas_submitted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_rfas_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_auth_id'], ['work_auths.id'], name=op.f('fk_rfas_work_auth_id_work_auths'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfas'))
    )
    op.create_table('rfa_building_codes',
    sa.Column('rfa_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'REMOVE', name='rfaaction'), nullable=False),
    sa.Column('budget_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['project_id', 'school_id'], ['project_school_links.project_id', 'project_school_links.school_id'], name=op.f('fk_rfa_building_codes_project_id_project_school_links'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfa_id'], ['rfas.id'], name=op.f('fk_rfa_building_codes_rfa_id_rfas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_rfa_building_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rfa_id', 'wa_code_id', 'project_id', 'school_id', name=op.f('pk_rfa_building_codes'))
    )
    op.create_table('rfa_project_codes',
    sa.Column('rfa_id', sa.Integer(), nullable=False),
    sa.Column('wa_code_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'REMOVE', name='rfaaction'), nullable=False),
    sa.ForeignKeyConstraint(['rfa_id'], ['rfas.id'], name=op.f('fk_rfa_project_codes_rfa_id_rfas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wa_code_id'], ['wa_codes.id'], name=op.f('fk_rfa_project_codes_wa_code_id_wa_codes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rfa_id', 'wa_code_id', name=op.f('pk_rfa_project_codes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfa_project_codes')
    op.drop_table('rfa_building_codes')
    op.drop_table('rfas')
    # ### end Alembic commands ###
