"""Added lab reports

Revision ID: e5a4fdb96484
Revises: fccee3519fd2
Create Date: 2026-04-27 21:46:09.510052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a4fdb96484'
down_revision: Union[str, Sequence[str], None] = 'fccee3519fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.drop_column('is_report')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_report', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
