"""added employee.display_name

Revision ID: f60a02bc3b29
Revises: 63cdb503fb16
Create Date: 2026-04-22 15:25:40.066779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60a02bc3b29'
down_revision: Union[str, Sequence[str], None] = '63cdb503fb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.create_unique_constraint(batch_op.f('uq_employees_display_name'), ['display_name'])
        batch_op.create_unique_constraint(batch_op.f('uq_employees_email'), ['email'])

    op.execute("UPDATE employees SET display_name = first_name || ' ' || last_name")

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('display_name', nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_employees_display_name'), ['display_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_employees_display_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
